export const images = {
  logo: require("../assets/images/Logo.svg"),
  dashboard: require("../assets/images/home-2.svg"),
  invoices: require("../assets/images/receipt-tax.svg"),
  messages: require("../assets/images/message.svg"),
  card: require("../assets/images/card.svg"),
  activity: require("../assets/images/group.svg"),
  analytics: require("../assets/images/Chart.svg"),
  getHelp: require("../assets/images/question-circle-outlined.svg"),
  settings: require("../assets/images/settings.svg"),
  search: require("../assets/images/Search.svg"),
  bell: require("../assets/images/bell.svg"),
  userImg: require("../assets/images/Ellipse 73.svg"),
  dashboardBanerImg: require("../assets/images/Mask Group.svg"),
  rightArrowIcon: require("../assets/images/arrow-narrow-right.svg"),
  bitcoinIcon: require("../assets/images/Frame 6.svg"),
  userTransactionIcon: require("../assets/images/img.svg"),
  paypalIcon: require("../assets/images/paypal.svg"),
};
